### ISSUE TITLE
code tag for mermaid

### ISSUE THREAD

**Issue by digitank** [parpalak/upmath.me#16]
Hi, i'm very glad for your work, because it's the only one solution for rendering markdown html mixed sites! :)
But i would need some escape in this for using mermaid.
i found the code tag, but it doesn't work for mermaid, the "<code>Browser-->Admin</code>" source will be reformatted as &gt, but i need the original > character in the next.

Or can i use mermaid in your solution?

**Comment by parpalak** [comment]
Hello, thanks for your question. I didn't actually get what you want to do. You can grab markdown code with latex images processed from this tab:
![image](https://user-images.githubusercontent.com/9402484/75374714-d3a45380-58dd-11ea-88e8-67049d91f18c.png)
Feel free to specify your question if it does not help.

I'm not going to support Mermaid because of KISS principle.
